/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_alaif_android_exif_UserComment */

#ifndef _Included_net_alaif_android_exif_UserComment
#define _Included_net_alaif_android_exif_UserComment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_alaif_android_exif_UserComment
 * Method:    getExifUserComment
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_alaif_android_exif_UserComment_getExifUserComment
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     net_alaif_android_exif_UserComment
 * Method:    putExifUserComment
 * Signature: ([B[B[B)I
 */
JNIEXPORT jint JNICALL Java_net_alaif_android_exif_UserComment_putExifUserComment
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
